name: philippeschaedler
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Hair Stylist Santa Monica California '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeaea'
    - '#030303'
    - '#898989'
    - '#464646'
    - '#e79167'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
