name: philippeschaedler
favicon: null
layout_spectrum: 0.26492800074629486
typography_spectrum: 0.00546307023614645
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8928199354559183
  lightness: 0.2639538743533194
  saturation: 0.3439425576943904
  rhythmicContrast: 0.7632313126232475
purpose: []
