name: philippeschaedler
favicon: null
layout_spectrum: 0.74428
typography_spectrum: 1
title: 'Hair Stylist Santa Monica California '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcc6dd'
    - '#7a91c7'
    - '#403a2f'
    - '#7e7058'
    - '#181813'
  brandStrength: 0
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
