name: philippeschaedler
favicon: null
layout_spectrum: 0.74428
typography_spectrum: 1
title: 'Hair Stylist Santa Monica California '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ada7a2'
    - '#535257'
    - '#737950'
    - '#272a2d'
    - '#cad0de'
  brandStrength: 1
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
