name: philippeschaedler
favicon: null
layout_spectrum: 0.26492800074629486
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeaea'
    - '#030303'
    - '#898989'
    - '#464646'
    - '#e79167'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.3439425576943904
  rhythmicContrast: 1
purpose: []
